GET   http://localhost:1000/student
###
POST   http://localhost:1000/student
Content-Type: application/json

{
    "_id":2,
    "name":"tushant",
    "subject":"CS"
}
###
DELETE  http://localhost:1000/student/2
###
PATCH  http://localhost:1000/student/1
Content-Type: application/json

{
    "_id":1,
    "name":"pasha",
    "subject":"maths"
}